apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jn298il66-python 
  janus-idp.io/tekton: jn298il66-python
  backstage.io/kubernetes-id: jn298il66-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jn298il66-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml